### ISSUE TITLE
[FEATURE] Allow Collection of different classes

### ISSUE THREAD

**Issue by priyanshunayan** [HTTP-APIs/hydra-python-core#43]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:

Currently there is no way to add collections consisting of different Hydra Classes. Although it's uncommon, it will be a nice feature to have.

Considering our default APIDOC: suppose there is abnormality over a certain region. So two companies A and B provided us Drones namely Drone A and Drone B. Both are having different set of features. So, we need to make two different classes DroneA and DroneB. Now one may want to see both types of Drones A and B listed in Drone Collection. 

Right now, doc_writer exposes API as `apidoc.add_supported_class(_class, collection=True)` thus making the collection limited to only one class. 

### Expected Behaviour:

One would be able to add multiple classes and multiple manages block to collection. like: `apidoc.add_collection([_class1, _class2], [manages1, manages2])`

**Comment by chrizandr** [comment]
Adding here for reference.

Something like this is still possible using a collection of Links. You have a collection of DroneA, another or DroneB and a collection of links that contain links to both resources in DroneA and DroneB. This is more of an issue with how the data is represented in the server and the API Doc. I think something like this is still possible with the current implementation of the core library. I agree that right now we have a strong dependency between the Collection and Class, but this was done on purpose in hydra to give semantic meaning to collections, rather than having them be a simple list. 

Something like this also becomes easier with the implementation suggested in HTTP-APIs/hydrus#416
